/* Parks Atlas — data. 63 U.S. National Parks, bilingual (zh/en).
   em (badge emoji) must stay unique across all 63 parks (ADR-0011).
   Adding/renaming parks: keep id stable — check-in records and cloud
   archives reference parks by id. */
const PARKS=[
{id:'acadia',en:'Acadia',zh:'阿卡迪亚',st:'缅因 ME',stEn:'Maine',yr:1919,lat:44.35,lng:-68.21,rg:'东北',em:'🌊',hl:'花岗岩海岸 + 凯迪拉克山日出',hlEn:'Granite coast + Cadillac Mountain sunrise',intro:'美国东海岸第一缕日出之地，花岗岩海岸、卵石滩与卡迪拉克山交织，秋色尤其惊艳。',introEn:'First place to catch the sunrise on the U.S. East Coast — granite shores, cobble beaches and Cadillac Mountain, stunning in the fall.'},
{id:'arches',en:'Arches',zh:'拱门',st:'犹他 UT',stEn:'Utah',yr:1971,lat:38.68,lng:-109.57,rg:'西南',em:'🪨',hl:'2000+ 天然石拱·精致拱门',hlEn:'2,000+ natural arches · Delicate Arch',intro:'地球上天然石拱最密集的地方，标志性的精致拱门（Delicate Arch）是犹他州的象征。',introEn:'The densest collection of natural stone arches on Earth; iconic Delicate Arch is the symbol of Utah.'},
{id:'badlands',en:'Badlands',zh:'荒地',st:'南达科他 SD',stEn:'South Dakota',yr:1978,lat:43.85,lng:-102.34,rg:'大平原',em:'⛰️',hl:'层叠土林 + 化石草原',hlEn:'Layered spires + fossil prairie',intro:'层层叠叠的尖峰与峡谷如外星地貌，黄昏时分色彩斑斓，草原上常见野牛与大角羊。',introEn:'Striped pinnacles and gullies like an alien world, glowing with color at dusk; bison and bighorn sheep roam the prairie.'},
{id:'bigbend',en:'Big Bend',zh:'大弯',st:'德州 TX',stEn:'Texas',yr:1944,lat:29.25,lng:-103.25,rg:'西南',em:'🏜️',hl:'格兰德河峡谷 + 极暗星空',hlEn:'Rio Grande canyons + darkest skies',intro:'沿着格兰德河的大转弯，奇瓦瓦沙漠、奇索斯山与峡谷并存，是全美最佳观星地之一。',introEn:'At the great bend of the Rio Grande, where the Chihuahuan Desert, Chisos Mountains and river canyons meet — some of the best stargazing in America.'},
{id:'biscayne',en:'Biscayne',zh:'比斯坎',st:'佛州 FL',stEn:'Florida',yr:1980,lat:25.49,lng:-80.21,rg:'东南',em:'🐠',hl:'95% 是水·珊瑚礁浮潜',hlEn:'95% water · snorkel the reefs',intro:'95% 的面积都在水下，红树林、珊瑚礁和沉船遗迹，是浮潜与划船的天堂。',introEn:'95% of it lies underwater: mangroves, coral reefs and shipwrecks make it a paradise for snorkeling and boating.'},
{id:'blackcanyon',en:'Black Canyon of the Gunnison',zh:'甘尼森黑峡谷',st:'科罗拉多 CO',stEn:'Colorado',yr:1999,lat:38.57,lng:-107.72,rg:'落基山',em:'🌑',hl:'狭深陡峭·阳光难入',hlEn:'Narrow, sheer, nearly sunless',intro:'峡谷又深又窄，部分谷底每天只有几十分钟阳光，垂直峭壁令人眩晕。',introEn:'A gorge so deep and narrow that parts of the floor get only minutes of sunlight a day; the sheer walls are dizzying.'},
{id:'bryce',en:'Bryce Canyon',zh:'布莱斯峡谷',st:'犹他 UT',stEn:'Utah',yr:1928,lat:37.57,lng:-112.18,rg:'西南',em:'🧡',hl:'红色岩柱林·日出圆剧场',hlEn:'Red hoodoo forest · sunrise amphitheater',intro:'成千上万根橙红色岩柱（hoodoo）组成天然圆剧场，日出时如燃烧的火焰。',introEn:'Thousands of orange-red hoodoos form a natural amphitheater that blazes like fire at sunrise.'},
{id:'canyonlands',en:'Canyonlands',zh:'峡谷地',st:'犹他 UT',stEn:'Utah',yr:1964,lat:38.20,lng:-109.93,rg:'西南',em:'🏞️',hl:'科罗拉多河切出的迷宫',hlEn:'A maze carved by the Colorado',intro:'科罗拉多河与绿河切出的辽阔峡谷迷宫，天空之岛观景台一览苍茫大地。',introEn:'A vast canyon labyrinth cut by the Colorado and Green rivers; the Island in the Sky mesa overlooks it all.'},
{id:'capitolreef',en:'Capitol Reef',zh:'国会礁',st:'犹他 UT',stEn:'Utah',yr:1971,lat:38.37,lng:-111.26,rg:'西南',em:'🍑',hl:'水褶皱 + 老果园',hlEn:'Waterpocket Fold + historic orchards',intro:'百英里长的地壳褶皱（Waterpocket Fold），还有先民留下的果园，可自摘水果。',introEn:'A hundred-mile wrinkle in the Earth’s crust — the Waterpocket Fold — plus pioneer orchards where you can pick your own fruit.'},
{id:'carlsbad',en:'Carlsbad Caverns',zh:'卡尔斯巴德洞窟',st:'新墨西哥 NM',stEn:'New Mexico',yr:1930,lat:32.17,lng:-104.44,rg:'西南',em:'🦇',hl:'巨型地下溶洞 + 蝙蝠群飞',hlEn:'Giant caverns + evening bat flights',intro:'深入地下的巨型石灰岩溶洞，夏夜数十万只蝙蝠倾巢而出的场面震撼。',introEn:'Enormous limestone caverns deep underground; on summer evenings hundreds of thousands of bats spiral out at once.'},
{id:'channelislands',en:'Channel Islands',zh:'海峡群岛',st:'加州 CA',stEn:'California',yr:1980,lat:34.01,lng:-119.42,rg:'加州',em:'🦭',hl:'加州的加拉帕戈斯',hlEn:'California’s Galápagos',intro:'被称作"北美的加拉帕戈斯"，只能坐船前往，海蚀洞划皮划艇、看海狮成群。',introEn:'Called “North America’s Galápagos” and reachable only by boat — kayak through sea caves and watch sea lions haul out in crowds.'},
{id:'congaree',en:'Congaree',zh:'康加里',st:'南卡 SC',stEn:'South Carolina',yr:2003,lat:33.79,lng:-80.78,rg:'东南',em:'🌳',hl:'全美最高阔叶林·萤火虫',hlEn:'Tallest hardwood forest · fireflies',intro:'北美最大的古老原始硬木泛滥林，参天巨树间架着木栈道，初夏有同步闪烁的萤火虫。',introEn:'North America’s largest old-growth bottomland hardwood forest, with boardwalks among giant trees and synchronous fireflies in early summer.'},
{id:'craterlake',en:'Crater Lake',zh:'火山口湖',st:'俄勒冈 OR',stEn:'Oregon',yr:1902,lat:42.94,lng:-122.10,rg:'西北',em:'💙',hl:'全美最深湖·极致蓝',hlEn:'Deepest U.S. lake · impossibly blue',intro:'火山喷发后塌陷形成的全美最深湖泊，湖水蓝得不可思议，环湖公路风景绝佳。',introEn:'America’s deepest lake, formed in a collapsed volcano; the water is an unbelievable blue and the rim drive is spectacular.'},
{id:'cuyahoga',en:'Cuyahoga Valley',zh:'凯霍加谷',st:'俄亥俄 OH',stEn:'Ohio',yr:2000,lat:41.26,lng:-81.57,rg:'中西部',em:'🚂',hl:'瀑布 + 复古观光火车',hlEn:'Waterfalls + a vintage scenic railroad',intro:'城市边缘的绿洲，布兰迪韦恩瀑布、运河步道，还能坐复古蒸汽小火车穿行。',introEn:'A green refuge on the edge of the city: Brandywine Falls, canal towpath trails, and a vintage scenic railroad running through.'},
{id:'deathvalley',en:'Death Valley',zh:'死亡谷',st:'加州/内华达',stEn:'California / Nevada',yr:1994,lat:36.51,lng:-117.08,rg:'加州',em:'🔥',hl:'北美最低最热·盐田星空',hlEn:'Lowest, hottest · salt flats and stars',intro:'北美海拔最低、最干最热之地，盐田、沙丘与彩色山丘并存，冬季是观星圣地。',introEn:'The lowest, driest, hottest place in North America — salt flats, dunes and painted hills, and superb winter stargazing.'},
{id:'denali',en:'Denali',zh:'德纳里',st:'阿拉斯加 AK',stEn:'Alaska',yr:1917,lat:63.33,lng:-150.50,rg:'阿拉斯加',em:'🏔️',hl:'北美最高峰 6190m·棕熊',hlEn:'North America’s highest peak · grizzlies',intro:'北美最高峰所在，一条公路深入苔原荒野，灰熊、驼鹿、北美驯鹿出没。',introEn:'Home of North America’s highest peak, with a single road running deep into tundra wilderness where grizzlies, moose and caribou roam.'},
{id:'drytortugas',en:'Dry Tortugas',zh:'干龟',st:'佛州 FL',stEn:'Florida',yr:1992,lat:24.63,lng:-82.87,rg:'东南',em:'🏰',hl:'海中古堡·只能坐船/水上飞机',hlEn:'Sea fortress · boat or seaplane only',intro:'远在墨西哥湾、只能乘船或水上飞机抵达，巨大的杰斐逊堡与清澈海水中的珊瑚。',introEn:'Far out in the Gulf and reachable only by boat or seaplane: massive Fort Jefferson and coral in crystal-clear water.'},
{id:'everglades',en:'Everglades',zh:'大沼泽',st:'佛州 FL',stEn:'Florida',yr:1934,lat:25.32,lng:-80.93,rg:'东南',em:'🐊',hl:'美洲鳄 + 红树湿地',hlEn:'Crocodiles + mangrove wetlands',intro:'北美最大的亚热带湿地，"流动的草河"，鳄鱼、短吻鳄、涉禽与海牛的家园。',introEn:'North America’s largest subtropical wetland, a “river of grass” — home to crocodiles, alligators, wading birds and manatees.'},
{id:'gatesarctic',en:'Gates of the Arctic',zh:'北极之门',st:'阿拉斯加 AK',stEn:'Alaska',yr:1980,lat:67.78,lng:-153.30,rg:'阿拉斯加',em:'🧊',hl:'全美访客最少·无路无径',hlEn:'Least visited · no roads, no trails',intro:'完全在北极圈内，没有路、没有步道、没有手机信号，是真正的极致荒野。',introEn:'Entirely above the Arctic Circle with no roads, no trails and no cell signal — wilderness at its most absolute.'},
{id:'gatewayarch',en:'Gateway Arch',zh:'圣路易斯拱门',st:'密苏里 MO',stEn:'Missouri',yr:2018,lat:38.62,lng:-90.19,rg:'中西部',em:'⛩️',hl:'192m 不锈钢大拱门',hlEn:'A 630-ft stainless steel arch',intro:'全美最小的国家公园，标志是 192 米高的不锈钢大拱门，可乘舱登顶俯瞰密西西比河。',introEn:'The smallest national park, crowned by the 630-foot stainless steel Gateway Arch — ride a tram pod to the top for Mississippi River views.'},
{id:'glacier',en:'Glacier',zh:'冰川',st:'蒙大拿 MT',stEn:'Montana',yr:1910,lat:48.70,lng:-113.72,rg:'落基山',em:'🐐',hl:'向阳大道·冰蚀湖群',hlEn:'Going-to-the-Sun Road · glacial lakes',intro:'"通往太阳之路"穿越壮丽群山，冰蚀湖、雪峰与山羊，号称"大陆的皇冠"。',introEn:'The Going-to-the-Sun Road crosses magnificent peaks, glacial lakes and mountain-goat country — the “Crown of the Continent.”'},
{id:'glacierbay',en:'Glacier Bay',zh:'冰川湾',st:'阿拉斯加 AK',stEn:'Alaska',yr:1980,lat:58.67,lng:-136.90,rg:'阿拉斯加',em:'🚢',hl:'潮水冰川崩塌·座头鲸',hlEn:'Calving tidewater glaciers · humpbacks',intro:'乘船驶入峡湾，看潮水冰川大块崩落入海，座头鲸、海獭、海豹随处可见。',introEn:'Cruise into the fjords to watch tidewater glaciers calve into the sea, with humpback whales, sea otters and seals all around.'},
{id:'grandcanyon',en:'Grand Canyon',zh:'大峡谷',st:'亚利桑那 AZ',stEn:'Arizona',yr:1919,lat:36.11,lng:-112.11,rg:'西南',em:'🌅',hl:'地球最壮观的峡谷',hlEn:'Earth’s most spectacular canyon',intro:'科罗拉多河历经数百万年切出的巨壑，层层岩壁记录着地球的历史，日落震撼人心。',introEn:'A mile-deep chasm carved by the Colorado over millions of years, its layered walls recording the Earth’s history; the sunsets are overwhelming.'},
{id:'grandteton',en:'Grand Teton',zh:'大提顿',st:'怀俄明 WY',stEn:'Wyoming',yr:1929,lat:43.73,lng:-110.80,rg:'落基山',em:'🫎',hl:'陡峭雪峰倒映湖中',hlEn:'Sheer peaks mirrored in lakes',intro:'提顿山脉拔地而起、没有缓坡，雪峰倒映在杰克逊湖与蛇河上，美得像明信片。',introEn:'The Tetons rise straight from the valley floor with no foothills, their snowy peaks mirrored in Jackson Lake and the Snake River — postcard-perfect.'},
{id:'greatbasin',en:'Great Basin',zh:'大盆地',st:'内华达 NV',stEn:'Nevada',yr:1986,lat:38.98,lng:-114.30,rg:'西南',em:'🌌',hl:'千年狐尾松 + 极暗夜空',hlEn:'Ancient bristlecones + dark skies',intro:'偏远而宁静，有世界最古老的狐尾松、地下溶洞和惊艳银河，游客稀少。',introEn:'Remote and quiet: the world’s oldest bristlecone pines, marble caves, a dazzling Milky Way, and very few crowds.'},
{id:'greatsanddunes',en:'Great Sand Dunes',zh:'大沙丘',st:'科罗拉多 CO',stEn:'Colorado',yr:2004,lat:37.79,lng:-105.59,rg:'落基山',em:'⏳',hl:'北美最高沙丘·沙上滑板',hlEn:'Tallest dunes · sandboarding',intro:'北美最高的沙丘紧贴雪山而立，可以在沙丘上滑沙板，春天脚下还有融雪溪流。',introEn:'North America’s tallest dunes stand against snowy peaks — sandboard down them, and in spring a snowmelt creek flows at their feet.'},
{id:'greatsmoky',en:'Great Smoky Mountains',zh:'大烟山',st:'田纳西/北卡',stEn:'Tennessee / North Carolina',yr:1934,lat:35.61,lng:-83.49,rg:'东南',em:'🌫️',hl:'全美访客最多·云雾森林',hlEn:'Most visited · misty forests',intro:'全美访客量最大的国家公园，云雾缭绕的山岭、丰富的野花与黑熊，秋色绝美。',introEn:'America’s most visited national park: mist-wreathed ridges, rich wildflowers, black bears and glorious fall color.'},
{id:'guadalupe',en:'Guadalupe Mountains',zh:'瓜达卢佩山',st:'德州 TX',stEn:'Texas',yr:1966,lat:31.92,lng:-104.87,rg:'西南',em:'🍂',hl:'德州最高峰·古海洋化石礁',hlEn:'Texas’s highest peak · fossil reef',intro:'德州最高峰所在，由古海洋化石礁抬升而成，秋天峡谷里的枫叶意外动人。',introEn:'Home to Texas’s highest peak, an uplifted ancient marine fossil reef; the fall maples in its canyons are an unexpected delight.'},
{id:'haleakala',en:'Haleakalā',zh:'哈雷阿卡拉',st:'夏威夷 HI',stEn:'Hawaii',yr:1961,lat:20.72,lng:-156.17,rg:'夏威夷',em:'☀️',hl:'云上看日出·火山口',hlEn:'Sunrise above the clouds · crater',intro:'毛伊岛上海拔 3000 米的休眠火山，云海之上看日出是此生难忘的体验。',introEn:'A 10,000-foot dormant volcano on Maui; watching the sunrise above the sea of clouds is unforgettable.'},
{id:'hawaii',en:'Hawaiʻi Volcanoes',zh:'夏威夷火山',st:'夏威夷 HI',stEn:'Hawaii',yr:1916,lat:19.38,lng:-155.20,rg:'夏威夷',em:'🌋',hl:'活火山·夜观熔岩红光',hlEn:'Active volcanoes · lava glow at night',intro:'大岛上的活火山，基拉韦厄火山口夜里泛着熔岩红光，见证大地的生长。',introEn:'Active volcanoes on the Big Island — Kīlauea’s crater glows lava-red at night as the land keeps growing.'},
{id:'hotsprings',en:'Hot Springs',zh:'温泉',st:'阿肯色 AR',stEn:'Arkansas',yr:1921,lat:34.51,lng:-93.05,rg:'东南',em:'♨️',hl:'百年浴场街·泡温泉',hlEn:'Historic Bathhouse Row · take a soak',intro:'全美最小巧的国家公园之一，历史悠久的"浴场街"可真正泡上一池古典温泉。',introEn:'One of the smallest national parks, with historic Bathhouse Row where you can actually soak in a classic thermal bath.'},
{id:'indianadunes',en:'Indiana Dunes',zh:'印第安纳沙丘',st:'印第安纳 IN',stEn:'Indiana',yr:2019,lat:41.65,lng:-87.05,rg:'中西部',em:'🏖️',hl:'密歇根湖畔沙丘海滩',hlEn:'Dunes and beaches on Lake Michigan',intro:'密歇根湖南岸的沙丘与海滩，远眺芝加哥天际线，植物多样性惊人。',introEn:'Dunes and beaches on Lake Michigan’s south shore, with the Chicago skyline in the distance and astonishing plant diversity.'},
{id:'isleroyale',en:'Isle Royale',zh:'罗亚尔岛',st:'密歇根 MI',stEn:'Michigan',yr:1940,lat:48.00,lng:-88.55,rg:'中西部',em:'🐺',hl:'苏必利尔湖中孤岛·狼与驼鹿',hlEn:'Remote island · wolves and moose',intro:'苏必利尔湖中的偏远孤岛，只能坐船或水上飞机去，狼与驼鹿的经典生态故事发生地。',introEn:'A remote island in Lake Superior, reached only by boat or seaplane — where the classic wolf-and-moose ecology story unfolded.'},
{id:'joshuatree',en:'Joshua Tree',zh:'约书亚树',st:'加州 CA',stEn:'California',yr:1994,lat:33.79,lng:-115.90,rg:'加州',em:'🌴',hl:'奇异树形 + 巨石攀爬·星空',hlEn:'Surreal trees + boulders · stars',intro:'两大沙漠交汇处，造型奇特的约书亚树与圆润巨石，是攀岩与观星的胜地。',introEn:'Where two deserts meet: surreal Joshua trees and rounded granite boulders, a mecca for climbing and stargazing.'},
{id:'katmai',en:'Katmai',zh:'卡特迈',st:'阿拉斯加 AK',stEn:'Alaska',yr:1980,lat:58.50,lng:-155.00,rg:'阿拉斯加',em:'🐻',hl:'棕熊瀑布捕鲑·胖熊周',hlEn:'Bears catching salmon · Fat Bear Week',intro:'布鲁克斯瀑布上棕熊跃起捕捉鲑鱼的画面世界闻名，秋天还有"胖熊大赛"。',introEn:'World-famous for brown bears snatching leaping salmon at Brooks Falls — and for Fat Bear Week every fall.'},
{id:'kenaifjords',en:'Kenai Fjords',zh:'基奈峡湾',st:'阿拉斯加 AK',stEn:'Alaska',yr:1980,lat:59.92,lng:-149.65,rg:'阿拉斯加',em:'🐋',hl:'出口冰川 + 观鲸游船',hlEn:'Exit Glacier + whale-watching cruises',intro:'巨大的哈丁冰原向海延伸出条条冰川，坐船看冰川崩塌、虎鲸与海鸟群。',introEn:'The vast Harding Icefield spills glaciers toward the sea; cruise out for calving ice, orcas and seabird colonies.'},
{id:'kingscanyon',en:'Kings Canyon',zh:'国王峡谷',st:'加州 CA',stEn:'California',yr:1940,lat:36.80,lng:-118.55,rg:'加州',em:'👑',hl:'巨杉 + 深峡谷',hlEn:'Giant sequoias + a profound canyon',intro:'与红杉国家公园相邻，既有格兰特将军巨杉，也有北美最深之一的峡谷。',introEn:'Adjacent to Sequoia: the General Grant Tree plus one of the deepest canyons in North America.'},
{id:'kobuk',en:'Kobuk Valley',zh:'科伯克谷',st:'阿拉斯加 AK',stEn:'Alaska',yr:1980,lat:67.55,lng:-159.28,rg:'阿拉斯加',em:'🦌',hl:'北极沙丘·驯鹿大迁徙',hlEn:'Arctic dunes · caribou migration',intro:'北极圈内不可思议的大沙丘，每年数十万头驯鹿在此渡河迁徙，几乎无人抵达。',introEn:'Improbable great dunes above the Arctic Circle, where hundreds of thousands of caribou ford the river each year; almost nobody makes it here.'},
{id:'lakeclark',en:'Lake Clark',zh:'克拉克湖',st:'阿拉斯加 AK',stEn:'Alaska',yr:1980,lat:60.97,lng:-153.42,rg:'阿拉斯加',em:'🎣',hl:'火山·棕熊·绿松石湖',hlEn:'Volcanoes · bears · turquoise lakes',intro:'火山、冰川、苔原与绿松石色湖泊俱全，棕熊在草滩上觅食，只能飞机进入。',introEn:'Volcanoes, glaciers, tundra and turquoise lakes all in one, with brown bears grazing the sedge flats — fly-in only.'},
{id:'lassen',en:'Lassen Volcanic',zh:'拉森火山',st:'加州 CA',stEn:'California',yr:1916,lat:40.49,lng:-121.51,rg:'加州',em:'🫧',hl:'沸泥塘 + 四种火山',hlEn:'Boiling mudpots + four volcano types',intro:'地球上四种火山齐聚一园，沸腾的泥塘、硫磺喷气孔与高山湖泊，像个微缩黄石。',introEn:'All four types of volcano in one park — boiling mudpots, sulfur vents and alpine lakes, like a miniature Yellowstone.'},
{id:'mammoth',en:'Mammoth Cave',zh:'猛犸洞',st:'肯塔基 KY',stEn:'Kentucky',yr:1941,lat:37.18,lng:-86.10,rg:'东南',em:'🕳️',hl:'全球最长洞穴系统',hlEn:'The world’s longest cave system',intro:'已探明长度世界第一的洞穴系统，幽深通道与地下大厅，随导览深入地底。',introEn:'The longest known cave system on Earth: deep passages and underground halls, explored on ranger-led tours.'},
{id:'mesaverde',en:'Mesa Verde',zh:'梅萨维德',st:'科罗拉多 CO',stEn:'Colorado',yr:1906,lat:37.23,lng:-108.46,rg:'落基山',em:'🏛️',hl:'悬崖上的古普韦布洛居所',hlEn:'Ancestral Puebloan cliff dwellings',intro:'保护着上千年前阿纳萨齐人建于悬崖之上的石屋聚落，是北美最珍贵的古迹之一。',introEn:'Preserves thousand-year-old Ancestral Puebloan stone villages built into the cliffs — among North America’s most precious ancient sites.'},
{id:'rainier',en:'Mount Rainier',zh:'瑞尼尔山',st:'华盛顿 WA',stEn:'Washington',yr:1899,lat:46.85,lng:-121.76,rg:'西北',em:'🗻',hl:'冰川火山 + 天堂花海',hlEn:'Glaciated volcano + Paradise meadows',intro:'高耸的冰川火山是西雅图的天际标志，夏季"天堂"草甸野花铺满山坡。',introEn:'The glaciered volcano that defines Seattle’s skyline; in summer the meadows at Paradise are carpeted with wildflowers.'},
{id:'newrivergorge',en:'New River Gorge',zh:'新河峡谷',st:'西弗吉尼亚 WV',stEn:'West Virginia',yr:2020,lat:37.95,lng:-81.06,rg:'东南',em:'🌉',hl:'最新国家公园·钢拱大桥漂流',hlEn:'Newest park · bridge + rafting',intro:'2020 年才升格、最年轻的国家公园，标志性大桥横跨古老峡谷，激流漂流与攀岩闻名。',introEn:'The youngest national park (2020): an iconic steel arch bridge spans an ancient gorge famous for whitewater rafting and climbing.'},
{id:'northcascades',en:'North Cascades',zh:'北喀斯喀特',st:'华盛顿 WA',stEn:'Washington',yr:1968,lat:48.70,lng:-121.20,rg:'西北',em:'❄️',hl:'300+ 冰川·阿尔卑斯锯峰',hlEn:'300+ glaciers · alpine sawteeth',intro:'被称作"美国的阿尔卑斯"，三百多条冰川与锯齿状山峰，松绿色的迪亚布洛湖醒目。',introEn:'“The American Alps”: more than 300 glaciers, jagged sawtooth peaks, and the striking turquoise of Diablo Lake.'},
{id:'olympic',en:'Olympic',zh:'奥林匹克',st:'华盛顿 WA',stEn:'Washington',yr:1938,lat:47.80,lng:-123.60,rg:'西北',em:'🍃',hl:'雨林+雪山+海岸三合一',hlEn:'Rainforest + peaks + coast in one',intro:'一园三貌：苔藓垂挂的温带雨林、终年积雪的高山、布满浮木的崎岖海岸。',introEn:'Three parks in one: moss-draped temperate rainforest, snowcapped mountains, and a rugged driftwood-strewn coast.'},
{id:'petrified',en:'Petrified Forest',zh:'石化林',st:'亚利桑那 AZ',stEn:'Arizona',yr:1962,lat:35.07,lng:-109.78,rg:'西南',em:'🪵',hl:'两亿年木化石 + 彩色荒漠',hlEn:'200-million-year logs + Painted Desert',intro:'两亿多年的树木化成五彩斑斓的石头，散落在彩绘沙漠的荒原上。',introEn:'Trees turned to rainbow-colored stone over 200 million years, scattered across the badlands of the Painted Desert.'},
{id:'pinnacles',en:'Pinnacles',zh:'尖峰石阵',st:'加州 CA',stEn:'California',yr:2013,lat:36.49,lng:-121.16,rg:'加州',em:'🦅',hl:'火山岩峰 + 加州神鹫',hlEn:'Volcanic spires + California condors',intro:'古火山残留的嶙峋岩峰与洞穴，是濒危的加州神鹫重新放归的家园。',introEn:'Craggy spires and talus caves left by an ancient volcano — a home where endangered California condors soar again.'},
{id:'redwood',en:'Redwood',zh:'红杉',st:'加州 CA',stEn:'California',yr:1968,lat:41.21,lng:-124.00,rg:'加州',em:'🐌',hl:'地球最高的树·海岸雾林',hlEn:'Tallest trees on Earth · fog forest',intro:'地球上最高的生物——海岸红杉就在这里，雾气缭绕的巨树林如远古秘境。',introEn:'The tallest living things on Earth — coast redwoods — rise through drifting fog like a primeval sanctuary.'},
{id:'rockymountain',en:'Rocky Mountain',zh:'落基山',st:'科罗拉多 CO',stEn:'Colorado',yr:1915,lat:40.34,lng:-105.68,rg:'落基山',em:'🐏',hl:'全美最高公路·高山苔原',hlEn:'Highest paved road · alpine tundra',intro:'翻越全美海拔最高的连续公路（Trail Ridge Rd），高山湖泊、苔原与马鹿成群。',introEn:'Drive Trail Ridge Road, the highest continuous paved road in the U.S., past alpine lakes, tundra and herds of elk.'},
{id:'saguaro',en:'Saguaro',zh:'萨瓜罗',st:'亚利桑那 AZ',stEn:'Arizona',yr:1994,lat:32.25,lng:-110.50,rg:'西南',em:'🌵',hl:'巨型仙人掌森林',hlEn:'A forest of giant cacti',intro:'成片高大的萨瓜罗仙人掌（可活两百年、高达十几米），是索诺兰沙漠的标志。',introEn:'Stands of towering saguaro cacti — living two centuries and growing forty feet tall — the emblem of the Sonoran Desert.'},
{id:'sequoia',en:'Sequoia',zh:'美洲杉/红杉',st:'加州 CA',stEn:'California',yr:1890,lat:36.49,lng:-118.57,rg:'加州',em:'🌲',hl:'世界体积最大的树',hlEn:'The largest tree on Earth',intro:'世界上体积最大的单体生物——谢尔曼将军树就在这里，巨杉林令人肃然起敬。',introEn:'Home of General Sherman, the largest single living thing on Earth by volume; the giant sequoia groves inspire awe.'},
{id:'shenandoah',en:'Shenandoah',zh:'谢南多厄',st:'弗吉尼亚 VA',stEn:'Virginia',yr:1935,lat:38.53,lng:-78.35,rg:'东南',em:'🍁',hl:'天际线大道·蓝岭秋色',hlEn:'Skyline Drive · Blue Ridge fall color',intro:'百英里长的"天际线大道"沿蓝岭山脉蜿蜒，秋天层林尽染、瀑布与黑熊相伴。',introEn:'The hundred-mile Skyline Drive winds along the Blue Ridge; in fall the forests blaze, with waterfalls and black bears for company.'},
{id:'theodore',en:'Theodore Roosevelt',zh:'西奥多·罗斯福',st:'北达科他 ND',stEn:'North Dakota',yr:1978,lat:46.98,lng:-103.54,rg:'大平原',em:'🐃',hl:'野牛野马 + 荒地牧场',hlEn:'Bison and wild horses in the badlands',intro:'为纪念热爱自然的老罗斯福总统而设，彩色荒地上野牛、野马与草原犬鼠成群。',introEn:'A tribute to conservationist president Theodore Roosevelt: painted badlands roamed by bison, wild horses and prairie dogs.'},
{id:'voyageurs',en:'Voyageurs',zh:'旅行者',st:'明尼苏达 MN',stEn:'Minnesota',yr:1975,lat:48.50,lng:-92.88,rg:'中西部',em:'🛶',hl:'水路相连·看北极光',hlEn:'Linked waterways · northern lights',intro:'以皮划艇与船相连的水上公园，湖岛交错，冬夜常能看到北极光。',introEn:'A park traveled by boat and canoe, all lakes and islands; on winter nights the northern lights often appear.'},
{id:'whitesands',en:'White Sands',zh:'白沙',st:'新墨西哥 NM',stEn:'New Mexico',yr:2019,lat:32.78,lng:-106.17,rg:'西南',em:'⬜',hl:'雪白石膏沙丘·滑沙',hlEn:'Gypsum dunes · sledding',intro:'世界最大的石膏白沙丘，洁白如雪、可滑沙，日落时染成粉金色。',introEn:'The world’s largest gypsum dunefield, white as snow — sled down the dunes and watch them turn pink and gold at sunset.'},
{id:'windcave',en:'Wind Cave',zh:'风洞',st:'南达科他 SD',stEn:'South Dakota',yr:1903,lat:43.57,lng:-103.48,rg:'大平原',em:'🌬️',hl:'罕见蜂窝状洞 + 地表野牛',hlEn:'Rare boxwork cave + bison prairie',intro:'地下是世界罕见的"箱状"蜂窝洞结构，地表是野牛与草原犬鼠的草原。',introEn:'Below ground, the world’s rarest “boxwork” honeycomb formations; above, a prairie of bison and prairie dogs.'},
{id:'wrangell',en:'Wrangell–St. Elias',zh:'兰格尔-圣伊莱亚斯',st:'阿拉斯加 AK',stEn:'Alaska',yr:1980,lat:61.00,lng:-142.00,rg:'阿拉斯加',em:'⛏️',hl:'全美最大·六个黄石那么大',hlEn:'Largest park · six Yellowstones',intro:'全美面积最大的国家公园，相当于六个黄石，火山、冰川与高峰一望无际。',introEn:'America’s largest national park — the size of six Yellowstones — volcanoes, glaciers and great peaks without end.'},
{id:'yellowstone',en:'Yellowstone',zh:'黄石',st:'怀俄明等',stEn:'Wyoming (& MT/ID)',yr:1872,lat:44.60,lng:-110.50,rg:'落基山',em:'🦬',hl:'世界第一座国家公园·间歇泉',hlEn:'The world’s first park · geysers',intro:'世界上第一座国家公园，老忠实间歇泉、大棱镜热泉与成群野牛、灰熊、狼。',introEn:'The world’s first national park: Old Faithful, Grand Prismatic Spring, and herds of bison alongside grizzlies and wolves.'},
{id:'yosemite',en:'Yosemite',zh:'优胜美地',st:'加州 CA',stEn:'California',yr:1890,lat:37.83,lng:-119.50,rg:'加州',em:'🌄',hl:'酋长岩 + 大瀑布·花岗岩殿堂',hlEn:'El Capitan + waterfalls · granite temple',intro:'花岗岩的殿堂：酋长岩、半圆顶与飞泻的瀑布，春天水量最盛，秋天宁静金黄。',introEn:'A temple of granite: El Capitan, Half Dome and plunging waterfalls — fullest in spring, golden and quiet in fall.'},
{id:'zion',en:'Zion',zh:'锡安',st:'犹他 UT',stEn:'Utah',yr:1919,lat:37.30,lng:-113.05,rg:'西南',em:'🧗',hl:'天使降临 + 涉水窄缝峡谷',hlEn:'Angels Landing + the Narrows',intro:'高耸的红色砂岩峡谷，"天使降临"步道与涉水穿行的"窄谷"是经典挑战。',introEn:'Soaring red sandstone canyons; the Angels Landing trail and wading the Narrows are the classic challenges.'},
{id:'virginislands',en:'Virgin Islands',zh:'维尔京群岛',st:'美属维尔京',stEn:'U.S. Virgin Islands',yr:1956,lat:18.34,lng:-64.73,rg:'属地',em:'🏝️',hl:'加勒比白沙滩 + 浮潜',hlEn:'Caribbean beaches + snorkeling',intro:'圣约翰岛上三分之二的土地，加勒比海的白沙滩、珊瑚礁与热带山林。',introEn:'Two-thirds of the island of St. John: Caribbean white-sand beaches, coral reefs and tropical forest.'},
{id:'samoa',en:'National Park of American Samoa',zh:'美属萨摩亚',st:'美属萨摩亚',stEn:'American Samoa',yr:1988,lat:-14.25,lng:-170.68,rg:'属地',em:'🌺',hl:'南太平洋雨林 + 珊瑚礁',hlEn:'South Pacific rainforest + reefs',intro:'美国唯一位于南半球的国家公园，南太平洋的热带雨林、珊瑚礁与狐蝠。',introEn:'The only U.S. national park south of the equator: South Pacific rainforest, coral reefs and flying foxes.'}
];
const STATES=[
{name:'Alabama',ab:'AL',zh:'阿拉巴马',m:'🏈'},{name:'Alaska',ab:'AK',zh:'阿拉斯加',m:'🐻‍❄️'},{name:'Arizona',ab:'AZ',zh:'亚利桑那',m:'🌵'},{name:'Arkansas',ab:'AR',zh:'阿肯色',m:'💎'},
{name:'California',ab:'CA',zh:'加州',m:'🐻'},{name:'Colorado',ab:'CO',zh:'科罗拉多',m:'🏔️'},{name:'Connecticut',ab:'CT',zh:'康涅狄格',m:'🌳'},{name:'Delaware',ab:'DE',zh:'特拉华',m:'🐔'},
{name:'District of Columbia',ab:'DC',zh:'华盛顿特区',m:'🏛️'},{name:'Florida',ab:'FL',zh:'佛州',m:'🐊'},{name:'Georgia',ab:'GA',zh:'佐治亚',m:'🍑'},{name:'Hawaii',ab:'HI',zh:'夏威夷',m:'🌺'},
{name:'Idaho',ab:'ID',zh:'爱达荷',m:'🥔'},{name:'Illinois',ab:'IL',zh:'伊利诺伊',m:'🌽'},{name:'Indiana',ab:'IN',zh:'印第安纳',m:'🏎️'},{name:'Iowa',ab:'IA',zh:'爱荷华',m:'🌽'},
{name:'Kansas',ab:'KS',zh:'堪萨斯',m:'🌻'},{name:'Kentucky',ab:'KY',zh:'肯塔基',m:'🐎'},{name:'Louisiana',ab:'LA',zh:'路易斯安那',m:'🎷'},{name:'Maine',ab:'ME',zh:'缅因',m:'🦞'},
{name:'Maryland',ab:'MD',zh:'马里兰',m:'🦀'},{name:'Massachusetts',ab:'MA',zh:'马萨诸塞',m:'🎓'},{name:'Michigan',ab:'MI',zh:'密歇根',m:'🚗'},{name:'Minnesota',ab:'MN',zh:'明尼苏达',m:'🛶'},
{name:'Mississippi',ab:'MS',zh:'密西西比',m:'🎸'},{name:'Missouri',ab:'MO',zh:'密苏里',m:'🎺'},{name:'Montana',ab:'MT',zh:'蒙大拿',m:'🦬'},{name:'Nebraska',ab:'NE',zh:'内布拉斯加',m:'🌽'},
{name:'Nevada',ab:'NV',zh:'内华达',m:'🎰'},{name:'New Hampshire',ab:'NH',zh:'新罕布什尔',m:'🍁'},{name:'New Jersey',ab:'NJ',zh:'新泽西',m:'🎢'},{name:'New Mexico',ab:'NM',zh:'新墨西哥',m:'🎈'},
{name:'New York',ab:'NY',zh:'纽约',m:'🗽'},{name:'North Carolina',ab:'NC',zh:'北卡',m:'✈️'},{name:'North Dakota',ab:'ND',zh:'北达科他',m:'🌾'},{name:'Ohio',ab:'OH',zh:'俄亥俄',m:'🌰'},
{name:'Oklahoma',ab:'OK',zh:'俄克拉荷马',m:'🤠'},{name:'Oregon',ab:'OR',zh:'俄勒冈',m:'🦫'},{name:'Pennsylvania',ab:'PA',zh:'宾州',m:'🔔'},{name:'Rhode Island',ab:'RI',zh:'罗德岛',m:'⚓'},
{name:'South Carolina',ab:'SC',zh:'南卡',m:'🌴'},{name:'South Dakota',ab:'SD',zh:'南达科他',m:'🗿'},{name:'Tennessee',ab:'TN',zh:'田纳西',m:'🎶'},{name:'Texas',ab:'TX',zh:'德州',m:'🤠'},
{name:'Utah',ab:'UT',zh:'犹他',m:'🏜️'},{name:'Vermont',ab:'VT',zh:'佛蒙特',m:'🍁'},{name:'Virginia',ab:'VA',zh:'弗吉尼亚',m:'🐦'},{name:'Washington',ab:'WA',zh:'华盛顿',m:'🍎'},
{name:'West Virginia',ab:'WV',zh:'西弗吉尼亚',m:'⛰️'},{name:'Wisconsin',ab:'WI',zh:'威斯康星',m:'🧀'},{name:'Wyoming',ab:'WY',zh:'怀俄明',m:'🦬'},{name:'Puerto Rico',ab:'PR',zh:'波多黎各',m:'🌴'}
];
/* Parks whose st label doesn't end in a 2-letter code: which state hosts them on the map */
const PARK_STATE_FALLBACK={deathvalley:'CA',greatsmoky:'TN',yellowstone:'WY'};
/* Region keys are the zh strings stored in each park's rg — canonical, do not translate here.
   English labels live in i18n.js (REGION_EN). */
const REGIONS=["东北","东南","落基山","西南","加州","西北","大平原","中西部","阿拉斯加","夏威夷","属地"];
/* [threshold, zh title, en title] — checked top-down */
const TIERS=[[63,"全图鉴大师","Atlas Master"],[50,"传奇旅人","Legendary Traveler"],[40,"资深玩家","Seasoned Collector"],[30,"旅行家","Traveler"],[15,"探索者","Explorer"],[5,"初心者","Beginner"],[1,"新手上路","First Steps"],[0,"未启程","Not Started"]];
window.PARKS=PARKS;window.STATES=STATES;window.PARK_STATE_FALLBACK=PARK_STATE_FALLBACK;window.REGIONS=REGIONS;window.TIERS=TIERS;
